import Head from 'next/head'
import PostList from '@/components/PostList/PostList'
import styles from '@/styles/index.module.scss'

export default function Home({posts}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.Main}>
        <div className={styles.containerMain}>
          <PostList postList={posts}/>
        </div>
      </main>
    </>
  )
}

export async function getStaticProps(){

  const res = await fetch("https://dummyjson.com/posts")
  const posts = await res.json()

  return{
    props:{
      posts: posts.posts
    }
  }
}